import React from 'react';
import {Audio, staticFile, useCurrentFrame} from 'remotion';

interface VoiceoverTrackProps {
  marketCode: string;
  text: string;
}

export const VoiceoverTrack: React.FC<VoiceoverTrackProps> = ({marketCode, text}) => {
  // Market-specific voiceover files
  // Generated by ElevenLabs API
  const voiceoverFile = `voiceover/${marketCode}-voiceover.mp3`;
  
  // For now, disable voiceover to avoid render errors
  // Will be enabled once we confirm audio files work
  const hasVoiceover = false;
  
  if (!hasVoiceover) {
    return null;
  }
  
  try {
    return (
      <Audio
        src={staticFile(voiceoverFile)}
        volume={1.0}
        startFrom={0}
      />
    );
  } catch (error) {
    console.error(`Error loading voiceover for ${marketCode}:`, error);
    return null;
  }
};
