import React from 'react';
import {Audio, staticFile, useCurrentFrame} from 'remotion';

interface VoiceoverTrackProps {
  marketCode: string;
  text: string;
}

export const VoiceoverTrack: React.FC<VoiceoverTrackProps> = ({marketCode, text}) => {
  // Market-specific voiceover files
  // In production: Generated by ElevenLabs API
  const voiceoverFiles: Record<string, string> = {
    JP: 'voiceover/japan-formal.mp3',
    SA: 'voiceover/saudi-arabic.mp3',
    IN: 'voiceover/india-hindi.mp3',
    DE: 'voiceover/germany-technical.mp3',
    BR: 'voiceover/brazil-portuguese.mp3',
    KR: 'voiceover/korea-modern.mp3',
    US: 'voiceover/original-english.mp3',
    GB: 'voiceover/uk-british.mp3',
    FR: 'voiceover/france-sophisticated.mp3',
    MX: 'voiceover/mexico-spanish.mp3',
  };
  
  const hasVoiceover = false; // Set to true when voiceover files are generated
  
  if (!hasVoiceover) {
    return null;
  }
  
  return (
    <Audio
      src={staticFile(voiceoverFiles[marketCode] || voiceoverFiles.US)}
      volume={1.0}
      startFrom={0}
    />
  );
};
