import React from 'react';
import {Audio, staticFile, useCurrentFrame} from 'remotion';

interface VoiceoverTrackProps {
  marketCode: string;
  text: string;
}

export const VoiceoverTrack: React.FC<VoiceoverTrackProps> = ({marketCode, text}) => {
  // Market-specific voiceover files
  // Generated by ElevenLabs API
  const voiceoverFiles: Record<string, string> = {
    JP: 'voiceover/JP-voiceover.mp3',
    SA: 'voiceover/SA-voiceover.mp3',
    IN: 'voiceover/IN-voiceover.mp3',
    DE: 'voiceover/DE-voiceover.mp3',
    BR: 'voiceover/BR-voiceover.mp3',
    KR: 'voiceover/KR-voiceover.mp3',
    US: 'voiceover/US-voiceover.mp3',
    GB: 'voiceover/GB-voiceover.mp3',
    FR: 'voiceover/FR-voiceover.mp3',
    MX: 'voiceover/MX-voiceover.mp3',
  };
  
  const hasVoiceover = true; // Enabled with ElevenLabs API key
  
  if (!hasVoiceover) {
    return null;
  }
  
  return (
    <Audio
      src={staticFile(voiceoverFiles[marketCode] || voiceoverFiles.US)}
      volume={1.0}
      startFrom={0}
    />
  );
};
